[package]
name = "foundry-cheatcodes"
description = "Foundry cheatcodes definitions and implementations"

version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
foundry-cheatcodes-spec.workspace = true
upstream-foundry-cheatcodes-spec = { git = "https://github.com/foundry-rs/foundry", tag = "v1.5.0", package = "foundry-cheatcodes-spec" }
edr_artifact.workspace = true
edr_common.workspace = true
edr_decoder_revert.workspace = true
foundry-compilers.workspace = true
foundry-evm-core.workspace = true
foundry-evm-traces.workspace = true

alloy-dyn-abi.workspace = true
alloy-primitives.workspace = true
alloy-genesis.workspace = true
alloy-sol-types.workspace = true
alloy-provider.workspace = true
alloy-rpc-types = { workspace = true, features = ["k256"] }
alloy-signer.workspace = true
alloy-signer-local = { workspace = true, features = [
    "mnemonic-all-languages",
    "keystore",
] }
alloy-consensus = { workspace = true, features = ["k256", "kzg"] }
alloy-rlp.workspace = true
alloy-chains.workspace = true
alloy-ens.workspace = true

base64.workspace = true
derive-where.workspace = true
dunce.workspace = true
dialoguer = "0.11"
eyre.workspace = true
itertools.workspace = true
jsonpath_lib.workspace = true
k256.workspace = true
memchr = "2.7"
p256 = "0.13"
ecdsa = "0.16"
rand.workspace = true
regex.workspace = true
revm.workspace = true
revm-inspectors.workspace = true
semver.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
tracing.workspace = true
walkdir.workspace = true
proptest.workspace = true
serde.workspace = true

[dev-dependencies]
alloy-json-abi.workspace = true
similar-asserts.workspace = true
