[package]
name = "edr_block_local"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-rlp.workspace = true
derive-where.workspace = true
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_chain_spec.workspace = true
edr_chain_spec_receipt.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_state_api.workspace = true
edr_state_persistent_trie.workspace = true
edr_transaction.workspace = true
edr_trie.workspace = true
edr_utils.workspace = true
itertools.workspace = true
thiserror.workspace = true

[features]
tracing = ["edr_chain_spec_receipt/tracing", "edr_state_persistent_trie/tracing"]

[lints]
workspace = true
