# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright 2021 contributors to the Rethnet project.

tab_spaces = 2
edition = "2021"
fn_single_line = false
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_try_shorthand = true
wrap_comments = true