[package]
name = "edr_mem_pool"
version.workspace = true
edition.workspace = true

[dependencies]
edr_chain_spec.workspace = true
edr_primitives.workspace = true
edr_state_api.workspace = true
edr_transaction.workspace = true
indexmap.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
edr_test_mem_pool.workspace = true
edr_test_transaction.workspace = true
paste.workspace = true

[features]
tracing = ["dep:tracing"]

[lints]
workspace = true
