[package]
name = "edr_blockchain_fork"
version.workspace = true
edition.workspace = true

[dependencies]
derive-where.workspace = true
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_block_remote.workspace = true
edr_block_storage.workspace = true
edr_blockchain_api.workspace = true
edr_blockchain_remote.workspace = true
edr_chain_config.workspace = true
edr_chain_spec.workspace = true
edr_chain_spec_rpc.workspace = true
edr_eip7892.workspace = true
edr_eth.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_rpc_eth.workspace = true
edr_state_api.workspace = true
edr_state_fork.workspace = true
edr_utils.workspace = true
log.workspace = true
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing = { workspace = true, optional = true }

[features]
test-remote = []
tracing = [
    "dep:tracing",
    "edr_block_storage/tracing",
    "edr_blockchain_api/tracing",
    "edr_blockchain_remote/tracing",
    "edr_state_fork/tracing"
]

[lints]
workspace = true

[dev-dependencies]
anyhow.workspace = true
edr_chain_l1.workspace = true
edr_chain_spec_provider.workspace = true
edr_defaults.workspace = true
edr_provider.workspace = true
edr_test_blockchain.workspace = true
edr_test_transaction.workspace = true
edr_test_utils.workspace = true
edr_transaction.workspace = true
serial_test = "2.0.0"
