[package]
name = "edr_eip7892"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-eips = { workspace = true, features = ["serde"] }
alloy-hardforks.workspace = true
serde.workspace = true

[lints]
workspace = true
