[package]
name = "edr_eip7892"
version.workspace = true
edition.workspace = true

[dependencies]
alloy-eips.workspace = true
alloy-hardforks.workspace = true
serde.workspace = true

[lints]
workspace = true
