[package]
name = "edr_cooldown_check"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata = "0.22"
clap.workspace = true
clap-cargo = { version = "0.17", features = ["cargo_metadata"] }
edr_defaults.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
chrono = {workspace = true, features = ["serde"]}
reqwest = {workspace = true, features = ["json", "gzip", "rustls-tls"]}
tokio = {workspace = true, features = ["macros", "rt-multi-thread", "time"]}
semver.workspace = true
futures = { version = "0.3", default-features = false, features = ["std"] }

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
