[package]
name = "edr_chain_spec_provider"
version.workspace = true
edition.workspace = true

[dependencies]
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_chain_config.workspace = true
edr_chain_spec.workspace = true
edr_chain_spec_block.workspace = true
edr_chain_spec_receipt.workspace = true
edr_chain_spec_rpc.workspace = true
edr_eip1559.workspace = true
edr_eip7892.workspace = true
edr_primitives.workspace = true
edr_transaction.workspace = true
serde.workspace = true

[features]
tracing = ["edr_chain_spec_block/tracing", "edr_chain_spec_receipt/tracing"]

[lints]
workspace = true
