[package]
name = "edr_block_builder_api"
version.workspace = true
edition.workspace = true

[dependencies]
edr_block_header.workspace = true
edr_blockchain_api.workspace = true
edr_chain_spec.workspace = true
edr_chain_spec_evm.workspace = true
edr_database_components.workspace = true
edr_primitives.workspace = true
edr_state_api.workspace = true
revm-precompile.workspace = true
thiserror.workspace = true

[features]
tracing = ["edr_blockchain_api/tracing", "edr_database_components/tracing", "edr_chain_spec_evm/tracing"]

[lints]
workspace = true
