[package]
name = "edr_block_miner"
version.workspace = true
edition.workspace = true

[dependencies]
edr_block_api.workspace = true
edr_block_builder_api.workspace = true
edr_block_header.workspace = true
edr_chain_spec.workspace = true
edr_chain_spec_block.workspace = true
edr_database_components.workspace = true
edr_chain_spec_evm.workspace = true
edr_mem_pool.workspace = true
edr_primitives.workspace = true
edr_signer.workspace = true
edr_state_api.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
edr_test_mem_pool.workspace = true
edr_test_transaction.workspace = true

[features]
tracing = ["dep:tracing", "edr_mem_pool/tracing"]

[lints]
workspace = true
