[package]
name = "edr_tool_generator_chain_config_op"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
git2 = "0.20.2"
itertools.workspace = true
log.workspace = true
op-revm.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml = { workspace = true, features = ["preserve_order"] }

[lints]
workspace = true
