[package]
name = "edr_evm"
version.workspace = true
edition.workspace = true

[dependencies]
edr_blockchain_api.workspace = true
edr_chain_spec.workspace = true
edr_database_components.workspace = true
edr_evm_spec.workspace = true
edr_precompile.workspace = true
edr_primitives.workspace = true
edr_state_api.workspace = true
tracing = { workspace = true, optional = true }

[features]
tracing = ["dep:tracing", "edr_blockchain_api/tracing", "edr_database_components/tracing", "edr_evm_spec/tracing"]

[lints]
workspace = true
