[package]
name = "edr_blockchain_api"
version.workspace = true
edition.workspace = true

[dependencies]
auto_impl.workspace = true
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_block_storage.workspace = true
edr_chain_spec.workspace = true
edr_eip7892.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_state_api.workspace = true
thiserror.workspace = true

[features]
tracing = ["edr_block_storage/tracing"]

[lints]
workspace = true
