[package]
name = "edr_blockchain_local"
version.workspace = true
edition.workspace = true

[dependencies]
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_block_storage.workspace = true
edr_blockchain_api.workspace = true
edr_chain_spec.workspace = true
edr_primitives.workspace = true
edr_receipt.workspace = true
edr_state_api.workspace = true
edr_state_persistent_trie.workspace = true
edr_utils.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
edr_blockchain_fork.workspace = true
edr_chain_l1.workspace = true
edr_chain_spec_provider.workspace = true
edr_defaults.workspace = true
edr_provider.workspace = true
edr_test_blockchain.workspace = true
edr_test_transaction.workspace = true
serial_test = "2.0.0"
tokio.workspace = true

[features]
tracing = ["dep:tracing", "edr_block_storage/tracing", "edr_blockchain_api/tracing", "edr_state_persistent_trie/tracing"]

[lints]
workspace = true
