[package]
name = "edr_tool_generator_dap"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
git2.workspace = true
serde_json.workspace = true
tempfile.workspace = true
toml.workspace = true
typify = { version = "0.5.0", default-features = false }

[lints]
workspace = true
