[package]
name = "edr_chain_spec_block"
version.workspace = true
edition.workspace = true

[dependencies]
edr_block_api.workspace = true
edr_block_builder_api.workspace = true
edr_block_header.workspace = true
edr_block_remote.workspace = true
edr_chain_spec.workspace = true
edr_chain_spec_evm.workspace = true
edr_chain_spec_receipt.workspace = true
edr_chain_spec_rpc.workspace = true
edr_utils.workspace = true

[features]
tracing = ["edr_block_builder_api/tracing", "edr_chain_spec_evm/tracing", "edr_chain_spec_receipt/tracing"]

[lints]
workspace = true
