[package]
name = "edr_debugger_tcp"
version.workspace = true
edition.workspace = true

[dependencies]
edr_debugger_bytecode.workspace = true
edr_debugger_protocol.workspace = true
serde_json.workspace = true

[dev-dependencies]
anyhow.workspace = true
edr_block_api.workspace = true
edr_block_header.workspace = true
edr_blockchain_api.workspace = true
edr_chain_l1.workspace = true
edr_defaults.workspace = true
edr_evm.workspace = true
edr_evm_spec.workspace = true
edr_primitives.workspace = true
edr_provider.workspace = true
edr_signer.workspace = true
edr_state_api.workspace = true
edr_test_blockchain.workspace = true
edr_test_utils.workspace = true

[lints]
workspace = true
