name: Open pre-release PR

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: Prepare pre-release PR
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          persist-credentials: false

      - uses: socketdev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 #v1
        with:
          mode: firewall

      - uses: ./.github/actions/setup-node

      - name: Install Dependencies
        run: sfw pnpm install --frozen-lockfile --prefer-offline

      - name: Get version from package.json
        id: get-version
        run: |
          STATUS="$RUNNER_TEMP/status.json"
          pnpm changeset status --output "$(realpath --relative-to=. "$STATUS")"
          VERSION="$(jq -r '.releases[] | select(.name == "@nomicfoundation/edr").newVersion' "$STATUS")"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update version & Create Pull Request
        uses: changesets/action@v1
        with:
          title: "edr-${{ steps.get-version.outputs.version }}"
          commit: "edr-${{ steps.get-version.outputs.version }}"
          version: "bash ./scripts/pre_release.sh"
        env:
          # If the default GITHUB_TOKEN is used, checks will not run in release PRs.
          # To have checks run, set up CHANGESETS_TOKEN in repo secrets with read/write
          # permission for Contents and Pull requests scopes.
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN || secrets.GITHUB_TOKEN }}
